[package]
name = "graphql-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.1"
async-graphql-warp = "7.0.1"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
warp = "0.3.6"
models = { path = "../models" }
http = "0.2.11"
