[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.1"
slab = "0.4.9"
tokio-postgres = "0.7.10"
serde = "1.0.195"
serde_postgres = "0.2.0"
scooby = "0.5.0"